# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

flow_val_covid19 <- function(x, u) {
    .Call('_UnbiasedMultilevel_flow_val_covid19', PACKAGE = 'UnbiasedMultilevel', x, u)
}

flow_grad_x0_covid19 <- function(x, u) {
    .Call('_UnbiasedMultilevel_flow_grad_x0_covid19', PACKAGE = 'UnbiasedMultilevel', x, u)
}

flow_grad_param_covid19 <- function(x, u) {
    .Call('_UnbiasedMultilevel_flow_grad_param_covid19', PACKAGE = 'UnbiasedMultilevel', x, u)
}

flow_vec <- function(x, u) {
    .Call('_UnbiasedMultilevel_flow_vec', PACKAGE = 'UnbiasedMultilevel', x, u)
}

Single_Time_Step_Explicit_covid19 <- function(dt, x, u, wvec, dmat) {
    .Call('_UnbiasedMultilevel_Single_Time_Step_Explicit_covid19', PACKAGE = 'UnbiasedMultilevel', dt, x, u, wvec, dmat)
}

init_weight_vector_covid19 <- function() {
    .Call('_UnbiasedMultilevel_init_weight_vector_covid19', PACKAGE = 'UnbiasedMultilevel')
}

init_d_matrix_covid19 <- function() {
    .Call('_UnbiasedMultilevel_init_d_matrix_covid19', PACKAGE = 'UnbiasedMultilevel')
}

init_weight_vector_high_order_covid19 <- function() {
    .Call('_UnbiasedMultilevel_init_weight_vector_high_order_covid19', PACKAGE = 'UnbiasedMultilevel')
}

init_d_matrix_high_order_covid19 <- function() {
    .Call('_UnbiasedMultilevel_init_d_matrix_high_order_covid19', PACKAGE = 'UnbiasedMultilevel')
}

forward_simulation_covid19 <- function(x0, u, tf, tstep) {
    .Call('_UnbiasedMultilevel_forward_simulation_covid19', PACKAGE = 'UnbiasedMultilevel', x0, u, tf, tstep)
}

forward_simulation_output_covid19 <- function(param, l) {
    .Call('_UnbiasedMultilevel_forward_simulation_output_covid19', PACKAGE = 'UnbiasedMultilevel', param, l)
}

observation_covid19 <- function(u, l) {
    .Call('_UnbiasedMultilevel_observation_covid19', PACKAGE = 'UnbiasedMultilevel', u, l)
}

observation_grad_covid19 <- function(u, l) {
    .Call('_UnbiasedMultilevel_observation_grad_covid19', PACKAGE = 'UnbiasedMultilevel', u, l)
}

inner_product_inverseproblem <- function(x0, x1) {
    .Call('_UnbiasedMultilevel_inner_product_inverseproblem', PACKAGE = 'UnbiasedMultilevel', x0, x1)
}

mat_inner_product_inverseproblem <- function(mle, x0, x1) {
    .Call('_UnbiasedMultilevel_mat_inner_product_inverseproblem', PACKAGE = 'UnbiasedMultilevel', mle, x0, x1)
}

compute_alpha_inverseproblem <- function(mle, d, r) {
    .Call('_UnbiasedMultilevel_compute_alpha_inverseproblem', PACKAGE = 'UnbiasedMultilevel', mle, d, r)
}

compute_beta_inverseproblem <- function(mle, d, rcg) {
    .Call('_UnbiasedMultilevel_compute_beta_inverseproblem', PACKAGE = 'UnbiasedMultilevel', mle, d, rcg)
}

sparse_mat_vec_mult_inverseproblem <- function(mle, x) {
    .Call('_UnbiasedMultilevel_sparse_mat_vec_mult_inverseproblem', PACKAGE = 'UnbiasedMultilevel', mle, x)
}

inverse_u_vec_inverseproblem <- function(umat, x) {
    .Call('_UnbiasedMultilevel_inverse_u_vec_inverseproblem', PACKAGE = 'UnbiasedMultilevel', umat, x)
}

inverse_l_vec_inverseproblem <- function(lmat, x) {
    .Call('_UnbiasedMultilevel_inverse_l_vec_inverseproblem', PACKAGE = 'UnbiasedMultilevel', lmat, x)
}

sparse_u_factor_inverseproblem <- function(mle) {
    .Call('_UnbiasedMultilevel_sparse_u_factor_inverseproblem', PACKAGE = 'UnbiasedMultilevel', mle)
}

sparse_l_factor_inverseproblem <- function(mle) {
    .Call('_UnbiasedMultilevel_sparse_l_factor_inverseproblem', PACKAGE = 'UnbiasedMultilevel', mle)
}

linear_solver_inverseproblem <- function(mle, b) {
    .Call('_UnbiasedMultilevel_linear_solver_inverseproblem', PACKAGE = 'UnbiasedMultilevel', mle, b)
}

cg_solver_inverseproblem <- function(mle, b) {
    .Call('_UnbiasedMultilevel_cg_solver_inverseproblem', PACKAGE = 'UnbiasedMultilevel', mle, b)
}

compute_matrix_dimension_inverseproblem <- function(nx) {
    .Call('_UnbiasedMultilevel_compute_matrix_dimension_inverseproblem', PACKAGE = 'UnbiasedMultilevel', nx)
}

init_system_matrix_inverseproblem <- function(param, nx) {
    .Call('_UnbiasedMultilevel_init_system_matrix_inverseproblem', PACKAGE = 'UnbiasedMultilevel', param, nx)
}

init_right_part_inverseproblem <- function(param, nx) {
    .Call('_UnbiasedMultilevel_init_right_part_inverseproblem', PACKAGE = 'UnbiasedMultilevel', param, nx)
}

numerical_solution_inverseproblem <- function(param, nx) {
    .Call('_UnbiasedMultilevel_numerical_solution_inverseproblem', PACKAGE = 'UnbiasedMultilevel', param, nx)
}

exact_solution_inverseproblem <- function(param, nx) {
    .Call('_UnbiasedMultilevel_exact_solution_inverseproblem', PACKAGE = 'UnbiasedMultilevel', param, nx)
}

numerical_solution_values_inverseproblem <- function(x, nval) {
    .Call('_UnbiasedMultilevel_numerical_solution_values_inverseproblem', PACKAGE = 'UnbiasedMultilevel', x, nval)
}

l2_norm_inverseproblem <- function(param, l) {
    .Call('_UnbiasedMultilevel_l2_norm_inverseproblem', PACKAGE = 'UnbiasedMultilevel', param, l)
}

init_system_matrix_derivative_inverseproblem <- function(param, pgrad, nx) {
    .Call('_UnbiasedMultilevel_init_system_matrix_derivative_inverseproblem', PACKAGE = 'UnbiasedMultilevel', param, pgrad, nx)
}

init_right_part_derivative_inverseproblem <- function(param, pgrad, nx) {
    .Call('_UnbiasedMultilevel_init_right_part_derivative_inverseproblem', PACKAGE = 'UnbiasedMultilevel', param, pgrad, nx)
}

numerical_solution_derivative_inverseproblem <- function(param, pgrad, nx) {
    .Call('_UnbiasedMultilevel_numerical_solution_derivative_inverseproblem', PACKAGE = 'UnbiasedMultilevel', param, pgrad, nx)
}

observation_points_inverseproblem <- function(nvec) {
    .Call('_UnbiasedMultilevel_observation_points_inverseproblem', PACKAGE = 'UnbiasedMultilevel', nvec)
}

observation_inverseproblem <- function(param, l) {
    .Call('_UnbiasedMultilevel_observation_inverseproblem', PACKAGE = 'UnbiasedMultilevel', param, l)
}

observation_grad_val_inverseproblem <- function(param, l, m) {
    .Call('_UnbiasedMultilevel_observation_grad_val_inverseproblem', PACKAGE = 'UnbiasedMultilevel', param, l, m)
}

observation_grad_inverseproblem <- function(param, l) {
    .Call('_UnbiasedMultilevel_observation_grad_inverseproblem', PACKAGE = 'UnbiasedMultilevel', param, l)
}

inner_product_toyexample <- function(x0, x1) {
    .Call('_UnbiasedMultilevel_inner_product_toyexample', PACKAGE = 'UnbiasedMultilevel', x0, x1)
}

mat_inner_product_toyexample <- function(mle, x0, x1) {
    .Call('_UnbiasedMultilevel_mat_inner_product_toyexample', PACKAGE = 'UnbiasedMultilevel', mle, x0, x1)
}

compute_alpha_toyexample <- function(mle, d, r) {
    .Call('_UnbiasedMultilevel_compute_alpha_toyexample', PACKAGE = 'UnbiasedMultilevel', mle, d, r)
}

compute_beta_toyexample <- function(mle, d, rcg) {
    .Call('_UnbiasedMultilevel_compute_beta_toyexample', PACKAGE = 'UnbiasedMultilevel', mle, d, rcg)
}

sparse_mat_vec_mult_toyexample <- function(mle, x) {
    .Call('_UnbiasedMultilevel_sparse_mat_vec_mult_toyexample', PACKAGE = 'UnbiasedMultilevel', mle, x)
}

inverse_u_vec_toyexample <- function(umat, x) {
    .Call('_UnbiasedMultilevel_inverse_u_vec_toyexample', PACKAGE = 'UnbiasedMultilevel', umat, x)
}

inverse_l_vec_toyexample <- function(lmat, x) {
    .Call('_UnbiasedMultilevel_inverse_l_vec_toyexample', PACKAGE = 'UnbiasedMultilevel', lmat, x)
}

sparse_u_factor_toyexample <- function(mle) {
    .Call('_UnbiasedMultilevel_sparse_u_factor_toyexample', PACKAGE = 'UnbiasedMultilevel', mle)
}

sparse_l_factor_toyexample <- function(mle) {
    .Call('_UnbiasedMultilevel_sparse_l_factor_toyexample', PACKAGE = 'UnbiasedMultilevel', mle)
}

linear_solver_direct_toyexample <- function(mle, d) {
    .Call('_UnbiasedMultilevel_linear_solver_direct_toyexample', PACKAGE = 'UnbiasedMultilevel', mle, d)
}

linear_solver_toyexample <- function(mle, b) {
    .Call('_UnbiasedMultilevel_linear_solver_toyexample', PACKAGE = 'UnbiasedMultilevel', mle, b)
}

cg_solver_toyexample <- function(mle, b) {
    .Call('_UnbiasedMultilevel_cg_solver_toyexample', PACKAGE = 'UnbiasedMultilevel', mle, b)
}

compute_matrix_dimension_toyexample <- function(nx) {
    .Call('_UnbiasedMultilevel_compute_matrix_dimension_toyexample', PACKAGE = 'UnbiasedMultilevel', nx)
}

init_system_matrix_toyexample <- function(param, nx) {
    .Call('_UnbiasedMultilevel_init_system_matrix_toyexample', PACKAGE = 'UnbiasedMultilevel', param, nx)
}

init_right_part_toyexample <- function(param, nx) {
    .Call('_UnbiasedMultilevel_init_right_part_toyexample', PACKAGE = 'UnbiasedMultilevel', param, nx)
}

numerical_solution_toyexample <- function(param, nx) {
    .Call('_UnbiasedMultilevel_numerical_solution_toyexample', PACKAGE = 'UnbiasedMultilevel', param, nx)
}

exact_solution_toyexample <- function(param, nx) {
    .Call('_UnbiasedMultilevel_exact_solution_toyexample', PACKAGE = 'UnbiasedMultilevel', param, nx)
}

numerical_solution_values_toyexample <- function(x, nval) {
    .Call('_UnbiasedMultilevel_numerical_solution_values_toyexample', PACKAGE = 'UnbiasedMultilevel', x, nval)
}

l2_norm_toyexample <- function(param, l) {
    .Call('_UnbiasedMultilevel_l2_norm_toyexample', PACKAGE = 'UnbiasedMultilevel', param, l)
}

init_system_matrix_derivative_toyexample <- function(param, pgrad, nx) {
    .Call('_UnbiasedMultilevel_init_system_matrix_derivative_toyexample', PACKAGE = 'UnbiasedMultilevel', param, pgrad, nx)
}

init_right_part_derivative_toyexample <- function(param, pgrad, nx) {
    .Call('_UnbiasedMultilevel_init_right_part_derivative_toyexample', PACKAGE = 'UnbiasedMultilevel', param, pgrad, nx)
}

numerical_solution_derivative_toyexample <- function(param, pgrad, nx) {
    .Call('_UnbiasedMultilevel_numerical_solution_derivative_toyexample', PACKAGE = 'UnbiasedMultilevel', param, pgrad, nx)
}

observation_points_toyexample <- function(nvec) {
    .Call('_UnbiasedMultilevel_observation_points_toyexample', PACKAGE = 'UnbiasedMultilevel', nvec)
}

observation_toyexample <- function(param, l) {
    .Call('_UnbiasedMultilevel_observation_toyexample', PACKAGE = 'UnbiasedMultilevel', param, l)
}

observation_grad_val_toyexample <- function(param, l, m) {
    .Call('_UnbiasedMultilevel_observation_grad_val_toyexample', PACKAGE = 'UnbiasedMultilevel', param, l, m)
}

observation_grad_toyexample <- function(param, l) {
    .Call('_UnbiasedMultilevel_observation_grad_toyexample', PACKAGE = 'UnbiasedMultilevel', param, l)
}

